language: python

python:
- '3.6'

script: true

install: true

before_install:
- openssl aes-256-cbc -K $encrypted_4cd85aa7abfc_key -iv $encrypted_4cd85aa7abfc_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

addons: true

after_success:
  - ssh root@$host "sh /data/etc/EOMS_update.sh"

