language: python

python:
- '3.6'

before_install:
- openssl aes-256-cbc -K $encrypted_4cd85aa7abfc_key -iv $encrypted_4cd85aa7abfc_iv
  -in ~/.ssh/id_rsa.enc -out ~/.ssh/id_rsa -d

after_success:
  - ssh root@47.95.0.177 "/data/etc/EOMS_update.sh"

addons:
  ssh_known_hosts: 47.95.0.177
