language: python

python:
- '3.6'

install:

script:

before_install:
- openssl aes-256-cbc -K $encrypted_4cd85aa7abfc_key -iv $encrypted_4cd85aa7abfc_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d

addons:
  ssh_known_hosts: 47.95.0.177

after_success:
  - ssh root@47.95.0.177 "sh /data/etc/EOMS_update.sh"

